### ISSUE TITLE
방금 커밋한 Chatbot.py 내용에 주석확인해줘!

### ISSUE THREAD

**Issue by Woojongkuk** [Woojongkuk/RecipeBot#1]
전체 chatbot코드 자체를 우리가 사용해야할 코드로 바꿔 봤어. 이 흐름대로 가면 될거같아!
주석부분에 코드 작성하면 돼

**Comment by hayoung131** [comment]
웅응 그 주석에따라 내가 사용자가 레시피명을 클릭했을때 부분 코딩하고, 예진이가 전체적 플로우랑 다 짰어!
