### ISSUE TITLE
DB 재료테이블에서 humanSentence와 유사도가 80%가 되야할 문제

### ISSUE THREAD

**Issue by Woojongkuk** [Woojongkuk/RecipeBot#2]
80% 이상인 것만 뽑아야 할 부분을 남인길 교수님께 여쭤봤는데
프로시져 IF문을 사용해보는 걸 추천하시더라고!
내가 공부해서 한 번 확인해볼테니까 답변해줘~

**Comment by hayoung131** [comment]
아아 그것도 괜찮은데 그것보단 내가 쿼리문을 짜봤거든??
`SELECT cooking_title,recipe_url
FROM mainrecipe
WHERE ((ingredient LIKE '%물%')+(ingredient LIKE '%설탕%')+(ingredient LIKE '%올리고당%')
+(ingredient LIKE '%다시마%')+(ingredient LIKE '%멸치가루%')+(ingredient LIKE '%양파%')
+(ingredient LIKE '%대파%'))/ingredient_num >=0.8;
`
이렇게하니까 80퍼센트이상 일치하는 레시피들의 타이틀과 url이 출력되더라고!! 이걸 사용하면 될거같아!
